import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import { useAuthState } from 'react-firebase-hooks/auth';
import { auth } from '../firebaseconfig';
export default function Home() {
	const [user, loading, error] = useAuthState(auth);
	return (
		<div>
			<Head>
				<title>Chat App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
			 	<section className='chat-section'>
					{user && <Sidebar/>	}
				</section>
			</main>

			<footer>
				
			</footer>
		</div>
	)
}
